import Head from 'next/head'
import { useState, useEffect } from 'react'

export default function Home() {

  useEffect(() => {
    //Runs only on the first render
    const data = localStorage.getItem('todos')
    if (data) {
      setTodos(JSON.parse(data))
    } else {
      localStorage.setItem("todos", JSON.stringify([]))
    }
  }, []);

  const [todos, setTodos] = useState([])
  const [bf, setBf] = useState({})
  const [display, setDisplay] = useState(1)


  var removeByAttr = function (arr, attr, value) { var i = arr.length; while (i--) { if (arr[i] && arr[i].hasOwnProperty(attr) && (arguments.length > 2 && arr[i][attr] === value)) { arr.splice(i, 1); } } return arr; }

  return (
    <div className='bg-slate-900 min-h-screen text-white'>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <div className='flex justify-center'>
        <div>

          <h1 className='text-4xl mt-20 font-extrabold text-center mb-10'>TODO App</h1>
          <div className='bg-white rounded p-2'>
            <input value={bf.todo} onChange={(e) => setBf({ id: todos.length + 1, todo: e.target.value, date: Date(), status: false })} className='focus:outline-none font-bold placeholder:text-gray-400 text-sm text-gray-900' placeholder='Add Tasks' type="text" />
            <button onClick={() => {
              if (bf.todo === "") return;
              if (!bf.todo) return;
              setTodos([...todos, bf]);
              const data = localStorage.getItem('todos')
              if (data) {
                localStorage.setItem('todos', JSON.stringify([...todos, bf]))
              }
              setBf({ id: todos.length + 1, todo: "", date: Date(), status: false });
            }} className='text-gray-800'>
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fillRule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clipRule="evenodd" />
              </svg>
            </button>
          </div>
        </div>
      </div>

      <div className='mt-10 flex justify-center'>
        <div>
          {todos.map((value, index) => {
            let date = value.date.substring(0, value.date.length - 40);
            let status;
            if (value.status) {
              status = "True"
            } else {
              status = "False"
            }
            //  GMT+0530 (India Standard Time) 
            return (
              <div key={value.id} className='flex max-w-5xl gap-5 md:gap-32 justify-between my-5 py-5 px-5 bg-slate-700 rounded '>

                <div>
                  <p className='text-lg'><b>{index + 1}.</b> {value.todo}</p>
                  <p className='text-sm mt-5 text-gray-300'><b>Date:</b> {date}</p>
                </div>

                <div className='flex'>
                  <button className='mr-' onClick={() => {

                    setTodos(todos.filter(v => {
                      if (v.date === value.date) {
                        v = !v;
                      }
                      return v;
                    }))

                    localStorage.setItem('todos', JSON.stringify(todos.filter(v => {
                      if (v.date === value.date) {
                        v = !v;
                      }
                      return v;
                    })))

                    window.location.reload();
                  }}>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-6 md:h-6 w-6 md:w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                    </svg>
                  </button>
                  
                </div>

              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}
